# Generated by Django 4.1.7 on 2023-03-29 07:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('event_image', models.ImageField(upload_to='eventimages/')),
                ('topic', models.TextField(max_length=500)),
                ('venue', models.TextField(max_length=200)),
                ('registration_fees', models.FloatField(default='Free')),
                ('paper_submited', models.BooleanField(default=False)),
                ('poster_submited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaperSubmition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=200)),
                ('paperfile', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('status', models.CharField(default='pending', max_length=50)),
                ('submit_count', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, max_length=1000, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.event')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PosterSubmition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postername', models.CharField(max_length=200)),
                ('posterabstract', models.CharField(max_length=200)),
                ('posterfile', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('status', models.CharField(default='pending', max_length=50)),
                ('submit_count', models.IntegerField(default=0)),
                ('posterremark', models.TextField(blank=True, max_length=1000, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.event')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('paper', models.BooleanField(default=False)),
                ('poster', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer_Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.postersubmition', unique=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer_Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.papersubmition', unique=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Privillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.BooleanField(default=False)),
                ('is_author', models.BooleanField(default=False)),
                ('is_reviewer', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=225)),
                ('designation', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images')),
                ('ph_no', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default=models.CharField(max_length=200, null=True), editable=False, max_length=100)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(default=models.CharField(max_length=200, null=True), editable=False, max_length=100)),
                ('Rstatus', models.CharField(default='v', max_length=1)),
                ('participant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.participanttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='targetted_audience',
            field=models.ManyToManyField(to='prof.participanttype'),
        ),
    ]
