# Generated by Django 4.1.7 on 2023-04-30 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prof", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="papersubmition",
            name="camera_ready_submition_status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="papersubmition",
            name="camera_ready_submition",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="camera_ready_submitions/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
