# Generated by Django 4.1.7 on 2023-03-16 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer_paper',
            name='papername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.papersubmition'),
        ),
        migrations.AlterField(
            model_name='reviewer_paper',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
