# Generated by Django 4.1.7 on 2023-05-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prof", "0002_papersubmition_camera_ready_submition_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papersubmition",
            name="camera_ready_submition_status",
            field=models.CharField(default="active", max_length=50),
        ),
    ]
