# Generated by Django 4.1.7 on 2023-03-16 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prof', '0002_alter_reviewer_paper_papername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer_Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.postersubmition')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
