# Generated by Django 4.1.7 on 2023-05-02 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prof", "0003_alter_papersubmition_camera_ready_submition_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contextsubmition",
            name="camera_ready_submition",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="camera_ready_submitions/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AddField(
            model_name="contextsubmition",
            name="camera_ready_submition_status",
            field=models.CharField(default="active", max_length=50),
        ),
        migrations.AddField(
            model_name="postersubmition",
            name="camera_ready_submition",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="camera_ready_submitions/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AddField(
            model_name="postersubmition",
            name="camera_ready_submition_status",
            field=models.CharField(default="active", max_length=50),
        ),
    ]
