# Generated by Django 4.1.7 on 2023-03-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_reviewer_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersubmition',
            name='remark',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='postersubmition',
            name='remark',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
