# Generated by Django 4.1.7 on 2023-05-03 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prof", "0004_contextsubmition_camera_ready_submition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="chair",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="co_chair",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Chair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventid", models.IntegerField()),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
