# Generated by Django 4.1.7 on 2023-05-04 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prof", "0006_event_chair_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="co_chair_id",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="prof.participant",
            ),
        ),
    ]
