# Generated by Django 4.1.7 on 2023-03-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0006_rename_posterremark_postersubmition_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postersubmition',
            old_name='remark',
            new_name='posterremark',
        ),
    ]
