# Generated by Django 4.1.7 on 2023-03-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0008_alter_papersubmition_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersubmition',
            name='remark',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='postersubmition',
            name='posterremark',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
