# Generated by Django 4.1.7 on 2023-05-04 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prof", "0009_remove_event_chair_remove_event_co_chair_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="chair_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chairid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="co_chair_id",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="co_chairid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
