# Generated by Django 4.1.7 on 2023-05-04 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prof", "0010_alter_event_chair_id_alter_event_co_chair_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="co_chair_id",
        ),
        migrations.AddField(
            model_name="event",
            name="co_chair_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="co_chairid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
