# Generated by Django 4.1.7 on 2023-05-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prof", "0011_remove_event_co_chair_id_event_co_chair_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cochair",
            name="userid",
        ),
        migrations.AddField(
            model_name="privillage",
            name="chair",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="privillage",
            name="co_chair",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Chair",
        ),
        migrations.DeleteModel(
            name="CoChair",
        ),
    ]
