# Generated by Django 4.1.7 on 2023-05-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prof", "0012_remove_cochair_userid_privillage_chair_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="papersubmition",
            name="admin_remark",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="papersubmition",
            name="chair_co_chair_remark",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
