# Generated by Django 4.1.7 on 2023-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prof", "0013_papersubmition_admin_remark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contextsubmition",
            name="admin_remark",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="contextsubmition",
            name="chair_co_chair_remark",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="postersubmition",
            name="admin_remark",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="postersubmition",
            name="chair_co_chair_remark",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
