# Generated by Django 4.1.7 on 2023-05-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prof", "0014_contextsubmition_admin_remark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(max_length=5000),
        ),
    ]
