# Generated by Django 4.1.7 on 2023-05-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prof", "0015_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewer_paper",
            name="papername",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="prof.papersubmition"
            ),
        ),
    ]
